#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1481018071                     # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : C IDE for iOS

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Adrian Labbé

your_link                                 : https://labbe.me

your_city                                 : Viña Del Mar
email_address                             : adrian@develobile.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : develobile
github_username                           : ColdGrub1384
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : LLVM
    description                           : You can compile C code into LLVM IR format with clang and interpret it with the lli command.
    fontawesome_icon_name                 : magic

  - title                                 : Multi files projects
    description                           : Create projects with multiple C Sources, Headers and libraries.
    fontawesome_icon_name                 : fokder-icon

  - title                                 : Code Editor
    description                           : Code editor with syntax highlighting and line numbers.
    fontawesome_icon_name                 : pen
    
  - title                                 : Terminal
    description                           : A terminal is included for running commands and your projects.
    fontawesome_icon_name                 : terminal
    
  - title                                 : Use your commands
    description                           : Install your commands in <a href="https://libterm.app">LibTerm</a>.
    fontawesome_icon_name                 : share

  - title                                 : Open Source
    description                           : SeeLess's source code is available on <a href="https://github.com/ColdGrub1384/SeeLess">GitHub</a>.
    fontawesome_icon_name                 : lock-open



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000000"

cover_image                               :                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ededed"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
